repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest ./tests
        language: system
        pass_filenames: false